swagger: "2.0"
info:
  title: Client panic test
paths:
  /v1/iaasresources:
    post:
      tags: ["iaasResources"]
      operationId: uploadIAASResources
      consumes:
      - text/plain
      parameters:
      - name: "iaasResources"
        required: true
        in: body
        schema:
          type: string
